# Generated by Django 3.2.11 on 2022-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
