# Generated by Django 3.2.11 on 2022-04-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(default='Unknown', max_length=400),
        ),
        migrations.AddField(
            model_name='card',
            name='domain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='historicPeriod',
            field=models.CharField(default='Unknown', max_length=400),
        ),
        migrations.AddField(
            model_name='card',
            name='land',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='birth',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='AnswerOptions',
        ),
    ]
