# Generated by Django 3.2.11 on 2022-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaapp', '0003_merge_0002_alter_card_image_0002_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(default='Unknown', max_length=400),
        ),
        migrations.AddField(
            model_name='card',
            name='domain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='land',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='birth',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
